model:
  type: lstm
  input_size: 40 # n_mfcc
  hidden_size: 256
  num_layers: 3
  bidirectional: true
  dropout: 0.2

data:
  cache_dir: data/cache
  feature: mfcc # mel | mfcc
  augmentation: true

training:
  epochs: 70
  batch_size: 64
  lr: 0.001
  workers: 4
  seed: 42
  early_stopping_patience: 10
  out_dir: results
